// Question bank for 1% Club (Party Edition), adapted from publicly reported
// episode recaps of The 1% Club (UK/US) — see specs/001-one-percent-club/plan.md
// Data Model for sourcing methodology, and README.md for the disclaimer.
// Generated by tools/gen-questions.js from tools/raw-questions.json — do not
// hand-edit this file directly; edit the raw data and regenerate instead.
// tier = reported percentage of the public who answered correctly (higher = easier).
export const QUESTIONS = [
  {
    "tier": 92,
    "q": "Which of these is the correct word for the crossword clue 'Investigate': EXPLORE, EXAMINE, or EXPOSE?",
    "a": "EXPLORE",
    "d": [
      "EXAMINE",
      "EXPOSE"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 92,
    "q": "At a zoo, the aardvark is called Adam, the meerkat is called Michelle, and the rhino is called Rochelle — each name starts with the same letter as the animal's name. What is the zebra called: Annabelle or Zachary?",
    "a": "Zachary",
    "d": [
      "Annabelle"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 92,
    "q": "Logically, given this exclusive guest list — Doja Cat, Megan Fox, Sheryl Crow — which of these celebrities also belongs on it: Bad Bunny, Ariana Grande, Post Malone, or Elton John?",
    "a": "Bad Bunny",
    "d": [
      "Ariana Grande",
      "Post Malone",
      "Elton John"
    ],
    "explain": "each name hides an animal: CAT, FOX, CROW, BUNNY",
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 80,
    "q": "Which name comes next in this sequence, where each surname's initials advance one letter through the alphabet: Ashley Banjo, Charles Dickens, Ella Fitzgerald, ____ ____?",
    "a": "Gloria Hunniford",
    "d": [
      "Gwyneth Paltrow",
      "Greta Thunberg"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 80,
    "q": "What single word do you get when you combine LEM, ON, and ADE in that order?",
    "a": "LEMONADE",
    "d": [
      "MELONADE",
      "LEMADEON",
      "ADELEMON"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 80,
    "q": "What is ABRACADABRA spelled backwards?",
    "a": "ARBADACARBA",
    "d": [
      "ARBRACADRBA",
      "ARBACADABRA"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 80,
    "q": "All the vowels and spaces have been removed from a headline, leaving LDYGGSNGSGRMMY. The full sentence uses the same single vowel five times. Which vowel is it?",
    "a": "A",
    "d": [
      "E",
      "I",
      "O"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 80,
    "q": "Fork is related by blood to Knife, but not to Spoon. Which two of the three could be identical twins?",
    "a": "Knife and Fork",
    "d": [
      "Fork and Spoon",
      "Knife and Spoon",
      "All three"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 80,
    "q": "Which of these symbols can be drawn without ever lifting your pen from the paper: %, !, &, or =?",
    "a": "!",
    "d": [
      "%",
      "&",
      "="
    ],
    "explain": "exclamation mark",
    "source": "https://moviedelic.com/the-1-club-episode-5-recap/"
  },
  {
    "tier": 80,
    "q": "Logically, what name fills the blank in this list: Jay, ____, Elle, Em?",
    "a": "Kay",
    "d": [
      "May",
      "Timothée Chalamet"
    ],
    "explain": "the names sound like the letters J, K, L, M",
    "source": "https://moviedelic.com/the-1-club-episode-8-recap/"
  },
  {
    "tier": 70,
    "q": "GERMANY contains the word MAN, and ARGENTINA contains the word GENT. Which of these countries has the word LAD hidden inside it: Spain, Morocco, or Bangladesh?",
    "a": "Bangladesh",
    "d": [
      "Spain",
      "Morocco"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 70,
    "q": "A cocktail is one-fifth vodka and 60% lemonade. What percentage of the cocktail is strawberry liqueur?",
    "a": "20%",
    "d": [
      "Two-fifths",
      "Two-thirds",
      "35%"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 70,
    "q": "One election candidate's name is an anagram of the words 'ELECTORAL SYSTEM'. What is the candidate's name?",
    "a": "Scarlett Moseley",
    "d": [
      "Marcella Toseley",
      "Selma Cartelroy",
      "Roselyn Attemscle"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 70,
    "q": "EVIL, VILE, and VEIL are all anagrams of one another using the same four letters. What other common four-letter word can be made from those same letters?",
    "a": "LIVE",
    "d": [
      "LEVI",
      "VEAL",
      "VILE"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 70,
    "q": "Susan's minivan seats 2 in front (including the driver), 2 in the middle row, and 3 in the back. How many kids can she safely take in one trip?",
    "a": "6",
    "d": [
      "5",
      "7",
      "8"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "If you replaced every vowel in the surname KARDASHIAN with a different vowel, which of these could be the new spelling: KURDUSHAUN, KIRDESHOON, or KORDOSHEEN?",
    "a": "KURDUSHAUN",
    "d": [
      "KIRDESHOON",
      "KORDOSHEEN"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "Selena and Camila are going to a 3-floor mall to shop for shoes, eat dinner, and see a movie — each activity is on a different floor. The theater is not on the 1st floor. Neither the 2nd nor 3rd floor has a shoe store. The food court is on the 2nd floor. Which floor is the shoe store on?",
    "a": "1st floor",
    "d": [
      "2nd floor",
      "3rd floor"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "Mike, Nell, and Tess take turns counting upward from 1 to 20, one number each, always in that same order (Mike, Nell, Tess, Mike, Nell, Tess...). Who says the number 20?",
    "a": "Nell",
    "d": [
      "Mike",
      "Tess"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "One of these three famous movie quotes has been misquoted. Which one? A) 'You can't handle the truth!' B) 'May the Force be with you.' C) 'Toto, I've a feeling we're in not Kansas anymore.'",
    "a": "C",
    "d": [
      "A",
      "B"
    ],
    "explain": "it should read 'we're not in Kansas anymore' — the words 'in' and 'not' are swapped",
    "source": "https://www.newsbreak.com/comingsoon-1584027/4046619232714-the-1-club-questions-answers-for-season-2-2025"
  },
  {
    "tier": 70,
    "q": "Two animal names can be joined together to spell a longer word that is NOT itself an animal. One of the animals is SEAL — what's the other animal, and what word do they make?",
    "a": "ANT",
    "d": [
      "OWL",
      "COW",
      "BAT"
    ],
    "explain": null,
    "source": "https://www.newsbreak.com/comingsoon-1584027/4287919353606-the-1-club-questions-answers-for-uk-season-5-2025"
  },
  {
    "tier": 70,
    "q": "A standard traffic light has green, yellow, and red lights. If the colors were rearranged in alphabetical order from top to bottom, what order would they be in?",
    "a": "Green, Red, Yellow",
    "d": [
      "Red, Yellow, Green",
      "Yellow, Green, Red"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "A faucet arrived with the words on its handles spelled backwards (a labeling mistake). The plumber who installed it also put the handles on the wrong sides. A second plumber then fixed just one of these two errors. If you turn the handle on the right now, what temperature water comes out?",
    "a": "Cold",
    "d": [
      "Hot",
      "Lukewarm"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 70,
    "q": "What animal do you get if you combine the sounds of the words BUN and KNEE?",
    "a": "BUNNY",
    "d": [
      "MONKEY",
      "DONKEY",
      "PUPPY"
    ],
    "explain": null,
    "source": "https://moviedelic.com/the-1-club-episode-5-recap/"
  },
  {
    "tier": 70,
    "q": "True or False: It would be False to say that the word 'True' appears more than the word 'False' in this True/False question?",
    "a": "True",
    "d": [
      "False"
    ],
    "explain": "the word 'False' actually appears more often, so it IS false that 'True' appears more — making the overall statement True",
    "source": "https://moviedelic.com/the-1-club-episode-8-recap/"
  },
  {
    "tier": 70,
    "q": "If a standard traffic light's colors were arranged alphabetically from top to bottom, what would the order be?",
    "a": "Green, red, yellow",
    "d": [
      "Green, yellow, red",
      "Red, green, yellow"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/06/09/the-1-club-6-8/"
  },
  {
    "tier": 70,
    "q": "What is the only month whose name becomes another common English word when spelled backwards?",
    "a": "May",
    "d": [
      "June",
      "March",
      "April"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 60,
    "q": "Four sisters get their hair cut one at a time. Steph goes sometime after Alisha. Holly goes first. Eliza goes sometime after Steph. Which order are they cut in: Holly, Alisha, Steph, Eliza; Alisha, Holly, Eliza, Steph; or Steph, Holly, Alisha, Eliza?",
    "a": "Holly, Alisha, Steph, Eliza",
    "d": [
      "Alisha, Holly, Eliza, Steph",
      "Steph, Holly, Alisha, Eliza"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 60,
    "q": "Using a consistent rule, SOFTENING becomes SONG, RADIOACTIVE becomes RAVE, and WHITECOAT becomes WHAT. What four-letter word does FAVOURITE become?",
    "a": "FATE",
    "d": [
      "FAVE",
      "FIRE",
      "FARE"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 60,
    "q": "One word in each of these correctly describes where its own capital letter sits: penultimatE, cenTral, iNitial. Which one is actually correct?",
    "a": "cenTral",
    "d": [
      "penultimatE",
      "iNitial"
    ],
    "explain": "the capital T is the middle/central letter of the word",
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 60,
    "q": "A turducken is a turkey stuffed with a duck stuffed with a chicken. Using that same naming logic, what should you call a burger stuffed with a taco stuffed with a pizza?",
    "a": "Burtaczza",
    "d": [
      "Tacoburzza",
      "Pizzurtaco",
      "Burgatapizz"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 60,
    "q": "A bee stung your tongue, so now every 'S' sound you make comes out as 'TH'. Based on the number of 'S' sounds in each word, which of these would give you the most trouble: Senselessness, Success, or Sunglasses?",
    "a": "Senselessness",
    "d": [
      "Success",
      "Sunglasses"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 60,
    "q": "What kind of storage room do you get by combining the words PAN and TREE?",
    "a": "PANTRY",
    "d": [
      "CELLAR",
      "CLOSET",
      "LARDER"
    ],
    "explain": null,
    "source": "https://moviedelic.com/the-1-club-episode-8-recap/"
  },
  {
    "tier": 50,
    "q": "What common two-word object do you get by combining the concepts of a SAFE, a TEABAG, and a BOWLING PIN?",
    "a": "Safety pin",
    "d": [
      "Bowling bag",
      "Locked bag",
      "Pin cushion"
    ],
    "explain": "SAFE + tea + PIN",
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 50,
    "q": "McHaley's Comet was seen in 2004, then again in 2011, 2018, and 2025 (every 7 years). Brady's Comet appeared in 1983, then 1999, and 2015 (every 16 years). Which comet will be seen next?",
    "a": "Brady's Comet",
    "d": [
      "McHaley's Comet",
      "They appear the same year"
    ],
    "explain": "due in 2031, before McHaley's in 2032",
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 50,
    "q": "If IYKYK means 'If you know, you know', which of these acronyms would stand for 'If you kayak, you know your kayak'?",
    "a": "IYKYKYK",
    "d": [
      "IYKYK2",
      "IYKAYAK",
      "IYKYKY"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 50,
    "q": "An alarm company requires a 10-character password with no repeated characters. Which of these passwords is acceptable: DISARM56$&, PASSWORD12, or SECURE1111?",
    "a": "DISARM56$&",
    "d": [
      "PASSWORD12",
      "SECURE1111"
    ],
    "explain": "all 10 characters are unique",
    "source": "https://bobbymgsk.wordpress.com/category/the-1-club/"
  },
  {
    "tier": 50,
    "q": "The first row combines pictures and a letter to make PENDANT. Which single letter completes the word in the second row?",
    "a": "A",
    "d": [
      "O",
      "E",
      "I"
    ],
    "explain": "CATALOG",
    "source": "https://moviedelic.com/the-1-club-episode-5-recap/",
    "image": "images/questions/cat-a-log.svg",
    "imageAlt": "A rebus diagram. The example row shows a pen, the letter D, and an ant, making PENDANT. The question row shows a cat, a blank box, and a log."
  },
  {
    "tier": 50,
    "q": "What animal logically comes next: Aardvark, Rabbit, Raccoon, Haddock, Honeybee, ___?",
    "a": "Giraffe",
    "d": [
      "Octopus",
      "Lobster"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 45,
    "q": "If the final question of the show was statistically twice as difficult (meaning half as many people could answer it), what would the new name of the show have to be?",
    "a": "The Half a % Club",
    "d": [
      "The 2% Club",
      "The 0.1% Club",
      "The 0.5% Club"
    ],
    "explain": null,
    "source": "https://moviedelic.com/the-1-club-episode-4-recap/"
  },
  {
    "tier": 45,
    "q": "Interlock your ten fingers with your left hand on the bottom. Starting with your lowest finger, which finger is sixth?",
    "a": "Right middle finger",
    "d": [
      "Right pinkie",
      "Left pointer finger",
      "Right ring finger"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/28/the-1-club-4-27/"
  },
  {
    "tier": 35,
    "q": "What word is spelled by the first letters of this clue: FIRST LETTERS OF WORDS EACH REALLY SPELL?",
    "a": "FLOWERS",
    "d": [
      "FIRST",
      "WORDS",
      "SPELL"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 30,
    "q": "ONION, TOMATO, and SALSA all share something in common: each word's first two letters are the same as its last two letters. Which of these also fits: EAGLE, RAZOR, BULB, or ERASER?",
    "a": "ERASER",
    "d": [
      "EAGLE",
      "RAZOR",
      "BULB"
    ],
    "explain": "starts and ends with ER",
    "source": "https://moviedelic.com/the-1-club-episode-4-recap/"
  },
  {
    "tier": 30,
    "q": "What one word in this question uses the greatest number of unique letters that aren't repeated?",
    "a": "QUESTION",
    "d": [
      "GREATEST",
      "NUMBER",
      "LETTERS"
    ],
    "explain": "all 8 letters are different",
    "source": "https://moviedelic.com/the-1-club-episode-5-recap/"
  },
  {
    "tier": 30,
    "q": "A wheel has three sections labeled 3 and three sections labeled 4. If you spin it twice, what percentage chance is there that the two spins total 7?",
    "a": "50%",
    "d": [
      "25%",
      "33%",
      "75%"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/14/the-1-club-3rd-s-p/"
  },
  {
    "tier": 30,
    "q": "A town named STATE is in a state named COUNTRY, which is in a country named TOWN. Which named place has the largest area?",
    "a": "TOWN",
    "d": [
      "STATE",
      "COUNTRY"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 25,
    "q": "In what year would someone born in 1990 turn the age equal to the sum of the digits in 1990?",
    "a": "2009",
    "d": [
      "1999",
      "2019",
      "2028"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/28/the-1-club-4-27/"
  },
  {
    "tier": 25,
    "q": "Someone's favorite instrument is TAMBOURINE, college major is EDUCATION, and favorite building is JAILHOUSE. By the same logic, which is their favorite vegetable?",
    "a": "CAULIFLOWER",
    "d": [
      "ASPARAGUS",
      "BRUSSELS SPROUTS",
      "RUTABAGA"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 25,
    "q": "CUSP, PINTO, QUARTS, ___, GALLEON: which word fills the blank so that removing one letter from each makes a unit of liquid measurement?",
    "a": "LOITER",
    "d": [
      "WINCE",
      "CINDER",
      "TEAL"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 20,
    "q": "How many syllables are there in total when you say the names of all 26 letters of the English alphabet?",
    "a": "28",
    "d": [
      "26",
      "29",
      "30"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/28/the-1-club-4-27/"
  },
  {
    "tier": 15,
    "q": "What vowel appears exactly four times in total when you write out the names of all seven days of the week?",
    "a": "U",
    "d": [
      "A",
      "E",
      "O"
    ],
    "explain": "in SUNDAY, TUESDAY, THURSDAY, and SATURDAY",
    "source": "https://moviedelic.com/the-1-club-episode-4-recap/"
  },
  {
    "tier": 15,
    "q": "Zora's birthday is the second-to-last day of the year and Lana's is the second day of the year. If today is Zora's birthday, how many days until Lana's?",
    "a": "3 days",
    "d": [
      "2 days",
      "4 days",
      "5 days"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 10,
    "q": "Delete the three letters of a horned farm animal from the word GERANIUMS to leave a common six-letter word. What is it?",
    "a": "GENIUS",
    "d": [
      "ENIGMA",
      "GAMINS",
      "REIGNS"
    ],
    "explain": "remove RAM",
    "source": "https://moviedelic.com/the-1-club-episode-4-recap/"
  },
  {
    "tier": 10,
    "q": "Combine the silent letters in INDICTED, HALFWAY, GUARD, AUTUMN, and KNUCKLE, in that order. What sound word do they spell?",
    "a": "CLUNK",
    "d": [
      "CLICK",
      "CLANG",
      "THUNK"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/14/the-1-club-3rd-s-p/"
  },
  {
    "tier": 5,
    "q": "Unscramble these letters to reveal a famous book and film character: AIMN OPPPRSY",
    "a": "MARY POPPINS",
    "d": [
      "NANNY MCPHEE",
      "PETER PAN",
      "ALICE PARSONS"
    ],
    "explain": null,
    "source": "https://quiz-questions.uk/1percentclub-quiz/"
  },
  {
    "tier": 5,
    "q": "If a name reversed spells a real word — for example, LIAM reversed is MAIL — what do you get if you reverse the name DENNIS?",
    "a": "SINNED",
    "d": [
      "SNIDEN",
      "DESNIN",
      "SINDEN"
    ],
    "explain": null,
    "source": "https://quiz-questions.uk/1percentclub-quiz/"
  },
  {
    "tier": 5,
    "q": "A coded sequence reads 3S46T89R5E7N68G46T52H9. Strip out all the numbers and you're left with a word inside a well-known three-word saying about continuous improvement. What is the saying?",
    "a": "Going from strength to strength",
    "d": [
      "Strength in numbers",
      "Practice makes perfect",
      "Onwards and upwards"
    ],
    "explain": null,
    "source": "https://quiz-questions.uk/1percentclub-quiz/"
  },
  {
    "tier": 5,
    "q": "What replaces the question marks in this sequence: JF3128, MA3130, MJ3130, ??????",
    "a": "JA3131",
    "d": [
      "JJ3130",
      "AS3131",
      "JA3130"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 5,
    "q": "Astrid, 32, meets Ed on a date. When she asks his age, he says: 'I'm really the same age as you, plus half my age.' How old is Ed?",
    "a": "64",
    "d": [
      "48",
      "56",
      "72"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-australia-065849278.html"
  },
  {
    "tier": 5,
    "q": "The four seasons can each be abbreviated to their first and last letters: SPRING becomes SG, SUMMER becomes SR, AUTUMN becomes AN. What letter completes WINTER's abbreviation, W?",
    "a": "R",
    "d": [
      "N",
      "T",
      "S"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 5,
    "q": "How many animals can you find hidden in this string of letters: PHEASANTORTOISEALLION?",
    "a": "6",
    "d": [
      "4",
      "5",
      "7"
    ],
    "explain": "PHEASANT, SEAL, SEALION, ANT, TORTOISE, LION",
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 5,
    "q": "Counting down from 100, what is the first number you say whose name is not contained within the name of another number with exactly one syllable?",
    "a": "Twelve",
    "d": [
      "Twenty",
      "Sixteen",
      "Ten"
    ],
    "explain": null,
    "source": "https://bobbymgsk.wordpress.com/2026/04/14/the-1-club-3rd-s-p/"
  },
  {
    "tier": 5,
    "q": "If A = 25, B = 24, C = 23, and so on, what do you get when you multiply the values of all the letters in MEGAHERTZ?",
    "a": "0",
    "d": [
      "25",
      "100",
      "1,000"
    ],
    "explain": null,
    "source": "https://www.comingsoon.net/guides/features/1987178-1-percent-club-questions-answers-season-2-2025-solutions-joel-mchale"
  },
  {
    "tier": 2,
    "q": "Which two countries need to be swapped so that this list is in the correct order: China, Oman, Russia, Thailand, Ethiopia, Croatia, Rwanda?",
    "a": "Thailand and Rwanda",
    "d": [
      "China and Croatia",
      "Oman and Ethiopia",
      "Russia and Rwanda"
    ],
    "explain": "spelling out C-O-R-R-E-C-T with their first letters",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "Lily is Pippa's niece, but she isn't Nicola's niece, even though Nicola is Pippa's sister and Pippa has no children. How is this possible?",
    "a": "Lily is Nicola's daughter",
    "d": [
      "Lily is adopted",
      "Nicola is not really her aunt",
      "Pippa is lying"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "What four-letter word do you get if you follow the directions in these three words: WRIGHT, RECENTER, CLEFT?",
    "a": "CREW",
    "d": [
      "CROWD",
      "WRECK",
      "CREEK"
    ],
    "explain": "C from cLEFT, RE from the centre of RECENTER, W from wRIGHT",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "JAMAICA + JAPAN share letters in positions that give the number 124. ARGENTINA + ARMENIA gives 1245. FRANCE + BRAZIL gives 23. What number does ENGLAND + GERMANY give?",
    "a": "56",
    "d": [
      "45",
      "67",
      "34"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "Manchester has a reputation for being rainy. If it's dry at 12:01am on Monday, what are the chances that it will be sunny exactly 72 hours later, on Thursday?",
    "a": "0%",
    "d": [
      "100%",
      "50%",
      "25%"
    ],
    "explain": "12:01am is night-time, so it can't be sunny regardless of weather",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "You walk 5 miles north, turn east and walk 7 miles, turn south and walk 5 miles, then turn west and walk 7 miles. How many miles away from your starting point are you?",
    "a": "0",
    "d": [
      "4",
      "14",
      "24"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "A day lasts approximately 10 hours on Jupiter. If you teleport there from the UK on Monday at 9am and stay for 8 Jupiter days, what day of the week is it in the UK when you teleport back?",
    "a": "Thursday",
    "d": [
      "Wednesday",
      "Friday",
      "Saturday"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "When the number 777,777 is written out fully in words, how many times does the letter 'e' appear?",
    "a": "14",
    "d": [
      "12",
      "13",
      "15"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "If you write the words HIGHER and LOWER out with their letters alternating (one letter from HIGHER, then one from LOWER, and so on), what do you get?",
    "a": "HLIOGWHEERR",
    "d": [
      "HILGOWHEERR",
      "HGIHOEWLRER",
      "HLOIGWHEREE"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "If you have eight fingers on your left hand, six fingers on your right hand, the same number of toes on your right foot as fingers on your left hand, and three toes on your left foot, how many fingers and toes do you have in total?",
    "a": "25",
    "d": [
      "22",
      "23",
      "27"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 2,
    "q": "In a room of 100 people, 99% are left-handed. How many left-handed people need to leave the room to bring that percentage down to 98%?",
    "a": "50",
    "d": [
      "1",
      "2",
      "25"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 2,
    "q": "Which four-letter word is missing from this list: spot, opts, pots, stop, tops, ____?",
    "a": "post",
    "d": [
      "stow",
      "spat",
      "stap"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Listen carefully: which letter of the alphabet is logically missing from this list — B, C, D, E, G, P, T, Z?",
    "a": "V",
    "d": [
      "F",
      "H",
      "Q"
    ],
    "explain": "all the given letters rhyme with 'ee' when said aloud, but V does not fit that same rhyming group with the missing letter",
    "source": "https://screenrant.com/1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "What word are you left with if you DEBUG this line of code: VANTIFLEACTOBEETLERTICKY?",
    "a": "VICTORY",
    "d": [
      "VANQUISH",
      "VALIANT",
      "VELOCITY"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Logically, which letter comes next in this sequence: S U M O T U W E T H F R S ?",
    "a": "A",
    "d": [
      "N",
      "U",
      "D"
    ],
    "explain": "each pair of letters is the start of a day of the week: SU, MO, TU, WE, TH, FR, SA",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Which letter pair could squeeze into the same position inside each of these words to make longer words: JUICE, PEERING, JEER?",
    "a": "ST",
    "d": [
      "TR",
      "RE",
      "AN"
    ],
    "explain": "JUSTICE, PESTERING, JESTER",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Using the letters in a spoonful of alphabet soup as many times as you like, what is the longest word you could spell?",
    "a": "INCONVENIENCED",
    "d": [
      "EXTRAORDINARY",
      "UNCONVENTIONAL",
      "INCONCEIVABLE"
    ],
    "explain": null,
    "source": "https://screenrant.com/1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Last month was not May or July. Next month is not January, March, or November. Neither last month nor next month is April, August, or December. What month must it be now?",
    "a": "April",
    "d": [
      "June",
      "September",
      "October"
    ],
    "explain": null,
    "source": "https://screenrant.com/1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "Take this jumbled string and remove the words 'two letters' from within it (letter by letter) to reveal a four-word phrase: T I W O A M L A W E T I N T E N R E S R",
    "a": "I AM A WINNER",
    "d": [
      "I AM THE WINNER",
      "WE ARE WINNERS",
      "I WIN AGAIN"
    ],
    "explain": null,
    "source": "https://screenrant.com/1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "When Vince got engaged, his best man bought balloons spelling STAG LOCATION. His other friends said he needed more balloons to spell CONGRATULATIONS instead. What three extra letters did he need to buy?",
    "a": "R, U, and N",
    "d": [
      "R, U, and T",
      "G, U, and N",
      "R, A, and N"
    ],
    "explain": "STAG LOCATION has one N, but CONGRATULATIONS needs two",
    "source": "https://www.ladbible.com/entertainment/tv/1-percent-club-question-difficult-congratulations-itv-572164-20260119"
  },
  {
    "tier": 1,
    "q": "You should always read the small print carefully. A block of Terms & Conditions is printed with no spaces between forty individual T&Cs. How many errors are hidden in the text?",
    "a": "7",
    "d": [
      "5",
      "6",
      "8"
    ],
    "explain": null,
    "source": "https://www.ladbible.com/entertainment/tv/1-percent-club-toughest-question-ever-151881-20251102"
  },
  {
    "tier": 1,
    "q": "Yolande takes one tablet every day of the week whose name contains exactly three vowels in total. She starts a pack of 10 tablets on March 2nd. What date will she need to start a new pack?",
    "a": "March 26th",
    "d": [
      "March 22nd",
      "March 30th",
      "April 2nd"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "A travel agent takes bookings: 54 for Lanzarote, 22 for Bali, 34 for Jamaica, 43 for Florida. Following the same rule (replacing a number with a word that starts with the digit it stands for), how many bookings did they take for Ibiza?",
    "a": "FLORIST",
    "d": [
      "FIFTY",
      "FOUR",
      "FORTY"
    ],
    "explain": null,
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "What letter completes this sequence, where each letter stands for a unit of time: S M H D W M ?",
    "a": "Y",
    "d": [
      "D",
      "C",
      "A"
    ],
    "explain": "Seconds, Minutes, Hours, Days, Weeks, Months, Years",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "What is the lowest whole number that is equal to ten times the number of letters in its own name when spelled out?",
    "a": "FIFTY",
    "d": [
      "FORTY",
      "SIXTY",
      "THIRTY"
    ],
    "explain": "50 = 10 × 5 letters",
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 1,
    "q": "A SPRAINED ANKLE represents an injury. Being told 'YOU ARE STUPID!' represents an insult. What well-known six-word phrase do the two together represent?",
    "a": "Adding insult to injury",
    "d": [
      "Rubbing salt in the wound",
      "Kicking someone while they're down",
      "A pain and an insult"
    ],
    "explain": null,
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-144833708.html"
  },
  {
    "tier": 1,
    "q": "What three-letter word can go before SON, FOOD, SICK, BED, and SIDE to make five new words?",
    "a": "SEA",
    "d": [
      "BED",
      "OUT",
      "AIR"
    ],
    "explain": "SEASON, SEAFOOD, SEASICK, SEABED, SEASIDE",
    "source": "https://www.yahoo.com/entertainment/1-club-questions-answers-uk-083757014.html"
  },
  {
    "tier": 1,
    "q": "Using the same rule throughout — replace the word 'times' with the multiplication symbol X to form words with similar meanings — TE x T equals MESSAGE, and TO x IN equals POISON. What two letters make E x ?? equal LEAVE?",
    "a": "IT",
    "d": [
      "GO",
      "ON",
      "UP"
    ],
    "explain": "EXIT",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "What number replaces the question mark: 1, 2, 3, 4, 5, 8, 7, 16, 9, ?",
    "a": "32",
    "d": [
      "18",
      "20",
      "64"
    ],
    "explain": "odd positions count up normally 1,3,5,7,9; even positions double each time: 2,4,8,16,32",
    "source": "https://quiz-questions.uk/1percentclub-quiz/"
  },
  {
    "tier": 1,
    "q": "What is the first number between 1 and 100 whose letters, when spelled out, are in alphabetical order?",
    "a": "FORTY",
    "d": [
      "EIGHT",
      "SIX",
      "FIFTY"
    ],
    "explain": "F, O, R, T, Y are in ascending alphabetical order",
    "source": "https://quiz-questions.uk/1percentclub-quiz/"
  },
  {
    "tier": 1,
    "q": "If January = 717, March = 5315, and June = 4624 (based on the number of letters in the month's name, its position in the calendar, and the product of those two numbers), what does August equal?",
    "a": "6848",
    "d": [
      "8648",
      "6488",
      "4868"
    ],
    "explain": "August has 6 letters, is the 8th month, and 6 × 8 = 48",
    "source": "https://www.tvguide.co.uk/articles/the-1-club-hardest-questions/"
  },
  {
    "tier": 1,
    "q": "What common three-letter word can be made from the three letters of the alphabet that do NOT appear anywhere in this sentence: 'Zeke's mighty quick jambalaya recipe is unviewed'?",
    "a": "FOX",
    "d": [
      "JAY",
      "ZIP",
      "BUY"
    ],
    "explain": "the letters F, O, and X do not appear in the sentence",
    "source": "https://moviedelic.com/the-1-club-episode-5-recap/"
  }
];
